"""Project 2 — Zombie Escape public API."""

from importlib import import_module
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from linkedin_visual_labs.projects.p04_zombie_escape.dl_model import (
        DLRiskMetrics,
        TrainedDLRiskModel,
        ZombieRiskCNN,
        configure_deterministic_torch,
        load_dl_checkpoint,
        persist_dl_risk_model,
        predict_dense_risk,
        train_dl_risk_model,
    )
    from linkedin_visual_labs.projects.p04_zombie_escape.dl_pipeline import (
        DLPipelineResult,
        merge_dl_predictions,
        predict_showcase_dl_risk_maps,
        run_dl_pipeline,
        solve_all_routes_from_persisted_predictions,
    )
    from linkedin_visual_labs.projects.p04_zombie_escape.dl_tensors import (
        INPUT_CHANNEL_COUNT,
        INPUT_CHANNELS,
        TARGET_NAME,
        CityTensor,
        city_to_tensor,
        validate_dl_input_contract,
    )

from linkedin_visual_labs.projects.p04_zombie_escape.city_generator import (
    GeneratedCity,
    HiddenRiskHotspot,
    ZombieZone,
    generate_all_cities,
    generate_city,
    terrain_is_traversable,
    terrain_speed_multiplier,
    validate_terrain_contract,
)
from linkedin_visual_labs.projects.p04_zombie_escape.config import (
    DEFAULT_CONFIG_PATH,
    load_zombie_config,
)
from linkedin_visual_labs.projects.p04_zombie_escape.evaluation import (
    HEADLINE_METHODS,
    REALIZED_RISK_WEIGHT,
    CityEvaluation,
    EvaluatedRoute,
    EvaluationArtifacts,
    EvaluationSummary,
    OverallMethodEvaluation,
    evaluate_routes_payload,
    normalized_objective_regret,
    realized_objective,
    run_evaluation,
    write_evaluation_artifacts,
)
from linkedin_visual_labs.projects.p04_zombie_escape.grid import (
    are_adjacent,
    four_neighbors,
    validate_grid_position,
)
from linkedin_visual_labs.projects.p04_zombie_escape.mission_visualization import (
    HEADING_HEIGHT,
    METHOD_LAYER_HEIGHT,
    MISSION_ENDPOINTS,
    RESULT_HEIGHT,
    SWARM_COUNTS,
    SWARM_SEEDS,
    MissionBox,
    MissionPreviewArtifacts,
    MissionTextPlacement,
    method_map_box,
    minimum_swarm_distance,
    mission_contract_payload,
    select_zombie_hotspots,
    validate_frame_geometry,
    validate_text_placements,
    write_mission_contract,
)
from linkedin_visual_labs.projects.p04_zombie_escape.ml_features import (
    FEATURE_COLUMNS,
    LABEL_COLUMN,
    observable_features,
    showcase_feature_frame,
    validate_no_feature_leakage,
)
from linkedin_visual_labs.projects.p04_zombie_escape.ml_model import (
    RiskModelMetrics,
    TrainedMLRiskModel,
    persist_ml_risk_model,
    predict_risk,
    train_ml_risk_model,
)
from linkedin_visual_labs.projects.p04_zombie_escape.ml_pipeline import (
    MLPipelineResult,
    predict_showcase_risk_maps,
    run_ml_pipeline,
)
from linkedin_visual_labs.projects.p04_zombie_escape.models import (
    AcceptanceDefinition,
    CityDefinition,
    CityId,
    CityProfile,
    CitySceneDefinition,
    DataOutputPaths,
    EncoderDefinition,
    EvaluationDefinition,
    ExperimentDefinition,
    GridCell,
    GridDefinition,
    GridPosition,
    LayerInternalGeometry,
    MethodCategory,
    MethodId,
    MethodLayerDefinition,
    ModelOutputPaths,
    MovementRule,
    OracleDefinition,
    OutputDefinition,
    OverviewGridDefinition,
    OverviewSceneDefinition,
    PixelRegion,
    PlannerCostDefinition,
    PlannerDefinition,
    ProjectMetadata,
    RiskDefinition,
    RiskEstimator,
    RouteMetrics,
    RoutePlanner,
    RouteResult,
    SummarySceneDefinition,
    TerrainDefinition,
    TerrainType,
    TrainingDefinition,
    TrainingSeeds,
    TypographyDefinition,
    VideoDefinition,
    VisualQualityDefinition,
    WinnerRule,
    ZombieConfigError,
    ZombieModelError,
    ZombieProjectConfig,
)
from linkedin_visual_labs.projects.p04_zombie_escape.pipeline import (
    ZombiePipelineContext,
    build_pipeline_context,
)
from linkedin_visual_labs.projects.p04_zombie_escape.routing import (
    PlannedPath,
    PlannerCostEngine,
    RiskLookup,
    RouteEvaluation,
    RoutePlanningError,
    astar_shortest_path,
    build_headline_route_result,
    compute_route_evaluation,
    compute_route_evaluation_with_threshold,
    dijkstra_shortest_path,
    mapping_risk_lookup,
    observed_dijkstra_route,
    observed_risk_lookup,
    oracle_astar_route,
    true_risk_lookup,
    validate_path_legality,
)
from linkedin_visual_labs.projects.p04_zombie_escape.serialization import (
    generated_cities_payload,
    serialize_generated_cities,
    write_generated_cities,
)
from linkedin_visual_labs.projects.p04_zombie_escape.visualization import (
    CANVAS_SIZE,
    CITY_LABELS,
    CITY_ORDER,
    METHOD_LABELS,
    PreviewArtifacts,
    VisualTheme,
    render_city_frame,
    render_final_summary,
    render_opening_board,
    render_preview_frames,
    validate_figure_geometry,
    validate_text_overlaps,
)

__all__ = [
    "CANVAS_SIZE",
    "CITY_LABELS",
    "CITY_ORDER",
    "DEFAULT_CONFIG_PATH",
    "FEATURE_COLUMNS",
    "HEADING_HEIGHT",
    "HEADLINE_METHODS",
    "INPUT_CHANNELS",
    "INPUT_CHANNEL_COUNT",
    "LABEL_COLUMN",
    "METHOD_LABELS",
    "METHOD_LAYER_HEIGHT",
    "MISSION_ENDPOINTS",
    "REALIZED_RISK_WEIGHT",
    "RESULT_HEIGHT",
    "SWARM_COUNTS",
    "SWARM_SEEDS",
    "TARGET_NAME",
    "AcceptanceDefinition",
    "CityDefinition",
    "CityEvaluation",
    "CityId",
    "CityProfile",
    "CitySceneDefinition",
    "CityTensor",
    "DLPipelineResult",
    "DLRiskMetrics",
    "DataOutputPaths",
    "EncoderDefinition",
    "EvaluatedRoute",
    "EvaluationArtifacts",
    "EvaluationDefinition",
    "EvaluationSummary",
    "ExperimentDefinition",
    "GeneratedCity",
    "GridCell",
    "GridDefinition",
    "GridPosition",
    "HiddenRiskHotspot",
    "LayerInternalGeometry",
    "MLPipelineResult",
    "MethodCategory",
    "MethodId",
    "MethodLayerDefinition",
    "MissionBox",
    "MissionPreviewArtifacts",
    "MissionTextPlacement",
    "ModelOutputPaths",
    "MovementRule",
    "OracleDefinition",
    "OutputDefinition",
    "OverallMethodEvaluation",
    "OverviewGridDefinition",
    "OverviewSceneDefinition",
    "PixelRegion",
    "PlannedPath",
    "PlannerCostDefinition",
    "PlannerCostEngine",
    "PlannerDefinition",
    "PreviewArtifacts",
    "ProjectMetadata",
    "RiskDefinition",
    "RiskEstimator",
    "RiskLookup",
    "RiskModelMetrics",
    "RouteEvaluation",
    "RouteMetrics",
    "RoutePlanner",
    "RoutePlanningError",
    "RouteResult",
    "SummarySceneDefinition",
    "TerrainDefinition",
    "TerrainType",
    "TrainedDLRiskModel",
    "TrainedMLRiskModel",
    "TrainingDefinition",
    "TrainingSeeds",
    "TypographyDefinition",
    "VideoDefinition",
    "VisualQualityDefinition",
    "VisualTheme",
    "WinnerRule",
    "ZombieConfigError",
    "ZombieModelError",
    "ZombiePipelineContext",
    "ZombieProjectConfig",
    "ZombieRiskCNN",
    "ZombieZone",
    "are_adjacent",
    "astar_shortest_path",
    "build_headline_route_result",
    "build_pipeline_context",
    "city_to_tensor",
    "compute_route_evaluation",
    "compute_route_evaluation_with_threshold",
    "configure_deterministic_torch",
    "dijkstra_shortest_path",
    "evaluate_routes_payload",
    "four_neighbors",
    "generate_all_cities",
    "generate_city",
    "generated_cities_payload",
    "load_dl_checkpoint",
    "load_zombie_config",
    "mapping_risk_lookup",
    "merge_dl_predictions",
    "method_map_box",
    "minimum_swarm_distance",
    "mission_contract_payload",
    "normalized_objective_regret",
    "observable_features",
    "observed_dijkstra_route",
    "observed_risk_lookup",
    "oracle_astar_route",
    "persist_dl_risk_model",
    "persist_ml_risk_model",
    "predict_dense_risk",
    "predict_risk",
    "predict_showcase_dl_risk_maps",
    "predict_showcase_risk_maps",
    "realized_objective",
    "render_city_frame",
    "render_final_summary",
    "render_opening_board",
    "render_preview_frames",
    "run_dl_pipeline",
    "run_evaluation",
    "run_ml_pipeline",
    "select_zombie_hotspots",
    "serialize_generated_cities",
    "showcase_feature_frame",
    "solve_all_routes_from_persisted_predictions",
    "terrain_is_traversable",
    "terrain_speed_multiplier",
    "train_dl_risk_model",
    "train_ml_risk_model",
    "true_risk_lookup",
    "validate_dl_input_contract",
    "validate_figure_geometry",
    "validate_frame_geometry",
    "validate_grid_position",
    "validate_no_feature_leakage",
    "validate_path_legality",
    "validate_terrain_contract",
    "validate_text_overlaps",
    "validate_text_placements",
    "write_evaluation_artifacts",
    "write_generated_cities",
    "write_mission_contract",
]


_DL_EXPORTS: dict[str, str] = {
    "DLRiskMetrics": "dl_model",
    "TrainedDLRiskModel": "dl_model",
    "ZombieRiskCNN": "dl_model",
    "configure_deterministic_torch": "dl_model",
    "load_dl_checkpoint": "dl_model",
    "persist_dl_risk_model": "dl_model",
    "predict_dense_risk": "dl_model",
    "train_dl_risk_model": "dl_model",
    "DLPipelineResult": "dl_pipeline",
    "merge_dl_predictions": "dl_pipeline",
    "predict_showcase_dl_risk_maps": "dl_pipeline",
    "run_dl_pipeline": "dl_pipeline",
    "solve_all_routes_from_persisted_predictions": "dl_pipeline",
    "INPUT_CHANNEL_COUNT": "dl_tensors",
    "INPUT_CHANNELS": "dl_tensors",
    "TARGET_NAME": "dl_tensors",
    "CityTensor": "dl_tensors",
    "city_to_tensor": "dl_tensors",
    "validate_dl_input_contract": "dl_tensors",
}


def __getattr__(name: str) -> Any:
    """Load optional deep-learning exports only when requested."""
    module_name = _DL_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    try:
        value = getattr(import_module(f"{__name__}.{module_name}"), name)
    except ModuleNotFoundError as exc:
        if exc.name == "torch":
            raise ModuleNotFoundError(
                "Zombie deep learning requires: pip install -e '.[zombie-dl]'",
                name="torch",
            ) from exc
        raise
    globals()[name] = value
    return value
