"""Reusable visualization system for Project 2."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Final, Protocol, cast

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.axes import Axes
from matplotlib.backend_bases import RendererBase
from matplotlib.figure import Figure
from matplotlib.patches import Patch
from matplotlib.text import Text

matplotlib.use("Agg")

CANVAS_SIZE: Final[int] = 1080
FIGURE_DPI: Final[int] = 100
FIGURE_INCHES: Final[float] = CANVAS_SIZE / FIGURE_DPI

CITY_ORDER: Final[tuple[str, ...]] = (
    "phoenix",
    "new_york",
    "chicago",
)

METHOD_ORDER: Final[tuple[str, ...]] = (
    "dijkstra",
    "ml",
    "dl",
)

METHOD_LABELS: Final[dict[str, str]] = {
    "dijkstra": "Dijkstra",
    "ml": "ML + A*",
    "dl": "Deep Learning + A*",
}

CITY_LABELS: Final[dict[str, str]] = {
    "phoenix": "Phoenix",
    "new_york": "New York",
    "chicago": "Chicago",
}


class _RendererCanvas(Protocol):
    """Canvas capable of exposing its active renderer."""

    def get_renderer(self) -> RendererBase:
        """Return the renderer used for the current figure."""
        ...


@dataclass(frozen=True, slots=True)
class VisualTheme:
    """Shared Project 2 visual constants."""

    background: str = "#08111f"
    panel_background: str = "#101c2d"
    panel_border: str = "#34465e"

    text_primary: str = "#f4f7fb"
    text_secondary: str = "#aab8cb"
    text_muted: str = "#71839c"

    building: str = "#263448"
    road: str = "#62728a"

    risk_low: str = "#1f7a5a"
    risk_medium: str = "#c48d2f"
    risk_high: str = "#a83d4d"

    dijkstra: str = "#54a6ff"
    ml: str = "#f3b64c"
    dl: str = "#cb6cff"

    winner: str = "#51d88a"

    title_size: int = 24
    subtitle_size: int = 13
    panel_title_size: int = 10
    metric_size: int = 9
    footer_size: int = 8

    route_width: float = 2.6


@dataclass(frozen=True, slots=True)
class PreviewArtifacts:
    """Preview frame outputs generated by Step 8."""

    opening_board: Path
    city_frames: tuple[Path, ...]
    final_summary: Path


THEME: Final[VisualTheme] = VisualTheme()


def load_visual_payloads(
    data_directory: Path,
) -> tuple[
    dict[str, object],
    dict[str, object],
    dict[str, object],
    dict[str, object],
]:
    """Load all persisted data used by visualization."""
    filenames = (
        "cities.json",
        "predicted_risk_maps.json",
        "routes.json",
        "evaluation_summary.json",
    )

    payloads = []

    for filename in filenames:
        path = data_directory / filename

        if not path.is_file():
            raise FileNotFoundError(f"visualization input missing: {path}")

        payloads.append(
            cast(
                dict[str, object],
                json.loads(path.read_text(encoding="utf-8")),
            )
        )

    return cast(
        tuple[
            dict[str, object],
            dict[str, object],
            dict[str, object],
            dict[str, object],
        ],
        tuple(payloads),
    )


def _new_figure() -> Figure:
    fig = plt.figure(
        figsize=(
            FIGURE_INCHES,
            FIGURE_INCHES,
        ),
        dpi=FIGURE_DPI,
        facecolor=THEME.background,
    )

    return fig


def _route_color(
    method_id: str,
) -> str:
    if method_id == "dijkstra":
        return THEME.dijkstra

    if method_id == "ml":
        return THEME.ml

    if method_id == "dl":
        return THEME.dl

    raise KeyError(f"unknown headline method: {method_id}")


def _city_payload(
    cities_payload: dict[str, object],
    city_id: str,
) -> dict[str, object]:
    raw_cities = cities_payload.get("cities")

    if isinstance(
        raw_cities,
        list,
    ):
        for city in raw_cities:
            if isinstance(city, dict) and city.get("city_id") == city_id:
                return cast(
                    dict[str, object],
                    city,
                )

    if isinstance(
        raw_cities,
        dict,
    ):
        city = raw_cities.get(city_id)

        if isinstance(
            city,
            dict,
        ):
            return cast(
                dict[str, object],
                city,
            )

    raise KeyError(f"city not found: {city_id}")


def _route_city_payload(
    routes_payload: dict[str, object],
    city_id: str,
) -> dict[str, object]:
    raw_cities = routes_payload.get("cities")

    if not isinstance(
        raw_cities,
        list,
    ):
        raise TypeError("routes.cities must be a list")

    for city in raw_cities:
        if isinstance(city, dict) and city.get("city_id") == city_id:
            return cast(
                dict[str, object],
                city,
            )

    raise KeyError(f"route city not found: {city_id}")


def _evaluation_city_payload(
    evaluation_payload: dict[str, object],
    city_id: str,
) -> dict[str, object]:
    raw_cities = evaluation_payload.get("cities")

    if not isinstance(
        raw_cities,
        list,
    ):
        raise TypeError("evaluation.cities must be a list")

    for city in raw_cities:
        if isinstance(city, dict) and city.get("city_id") == city_id:
            return cast(
                dict[str, object],
                city,
            )

    raise KeyError(f"evaluation city not found: {city_id}")


def _position(
    raw: object,
) -> tuple[int, int]:
    if not isinstance(
        raw,
        dict,
    ):
        raise TypeError("serialized position must be an object")

    row = raw.get("row")

    column = raw.get("column")

    if not isinstance(
        row,
        int,
    ) or not isinstance(
        column,
        int,
    ):
        raise TypeError("position row/column must be integers")

    return (
        row,
        column,
    )


def _cells(
    city: dict[str, object],
) -> list[dict[str, object]]:
    raw = city.get("cells")

    if not isinstance(
        raw,
        list,
    ):
        raise TypeError("city.cells must be a list")

    result = []

    for cell in raw:
        if not isinstance(
            cell,
            dict,
        ):
            raise TypeError("city cell must be an object")

        result.append(
            cast(
                dict[str, object],
                cell,
            )
        )

    return result


def _cell_position(
    cell: dict[str, object],
) -> tuple[int, int]:
    position = cell.get("position")

    if isinstance(
        position,
        dict,
    ):
        return _position(position)

    row = cell.get("row")

    column = cell.get("column")

    if isinstance(
        row,
        int,
    ) and isinstance(
        column,
        int,
    ):
        return (
            row,
            column,
        )

    raise TypeError("cell position unavailable")


def _terrain_name(
    cell: dict[str, object],
) -> str:
    raw = cell.get("terrain")

    if isinstance(
        raw,
        str,
    ):
        return raw.lower()

    if isinstance(
        raw,
        dict,
    ):
        value = raw.get("value")

        if isinstance(
            value,
            str,
        ):
            return value.lower()

    return "open"


def _observed_risk(
    cell: dict[str, object],
) -> float:
    value = cell.get(
        "observed_risk",
        0.0,
    )

    if isinstance(
        value,
        (int, float),
    ) and not isinstance(
        value,
        bool,
    ):
        return float(value)

    return 0.0


def _city_dimensions(
    city: dict[str, object],
) -> tuple[int, int]:
    cells = _cells(city)

    positions = [_cell_position(cell) for cell in cells]

    rows = max(row for row, _ in positions) + 1

    columns = max(column for _, column in positions) + 1

    return (
        rows,
        columns,
    )


def _risk_matrix(
    city: dict[str, object],
) -> np.ndarray:
    rows, columns = _city_dimensions(city)

    matrix = np.zeros(
        (
            rows,
            columns,
        ),
        dtype=float,
    )

    for cell in _cells(city):
        row, column = _cell_position(cell)

        matrix[
            row,
            column,
        ] = _observed_risk(cell)

    return matrix


def _building_mask(
    city: dict[str, object],
) -> np.ndarray:
    rows, columns = _city_dimensions(city)

    matrix = np.zeros(
        (
            rows,
            columns,
        ),
        dtype=float,
    )

    for cell in _cells(city):
        row, column = _cell_position(cell)

        if "building" in _terrain_name(cell):
            matrix[
                row,
                column,
            ] = 1.0

    return matrix


def _draw_city_base(
    ax: Axes,
    city: dict[str, object],
) -> None:
    risk = _risk_matrix(city)

    buildings = _building_mask(city)

    ax.set_facecolor(THEME.panel_background)

    ax.imshow(
        risk,
        cmap="magma",
        vmin=0.0,
        vmax=1.0,
        interpolation="nearest",
        alpha=0.72,
        origin="upper",
    )

    building_overlay = np.ma.masked_where(
        buildings <= 0.0,
        buildings,
    )

    ax.imshow(
        building_overlay,
        cmap=matplotlib.colors.ListedColormap(
            [
                THEME.building,
            ]
        ),
        interpolation="nearest",
        alpha=1.0,
        origin="upper",
    )

    rows, columns = risk.shape

    ax.set_xlim(
        -0.5,
        columns - 0.5,
    )

    ax.set_ylim(
        rows - 0.5,
        -0.5,
    )

    ax.set_xticks([])

    ax.set_yticks([])

    for spine in ax.spines.values():
        spine.set_edgecolor(THEME.panel_border)

        spine.set_linewidth(1.0)


def _method_route(
    routes_payload: dict[str, object],
    city_id: str,
    method_id: str,
) -> dict[str, object]:
    city = _route_city_payload(
        routes_payload,
        city_id,
    )

    methods = city.get("methods")

    if not isinstance(
        methods,
        dict,
    ):
        raise TypeError("route methods must be an object")

    route = methods.get(method_id)

    if not isinstance(
        route,
        dict,
    ):
        raise KeyError(f"{city_id}.{method_id} route missing")

    return cast(
        dict[str, object],
        route,
    )


def _draw_route(
    ax: Axes,
    route: dict[str, object],
    method_id: str,
) -> None:
    path = route.get("path")

    if (
        not isinstance(
            path,
            list,
        )
        or not path
    ):
        raise ValueError("route path missing")

    positions = [_position(raw) for raw in path]

    rows = [row for row, _ in positions]

    columns = [column for _, column in positions]

    color = _route_color(method_id)

    ax.plot(
        columns,
        rows,
        linewidth=THEME.route_width,
        color=color,
        solid_capstyle="round",
        solid_joinstyle="round",
        zorder=5,
    )

    ax.scatter(
        [
            columns[0],
        ],
        [
            rows[0],
        ],
        s=25,
        color=THEME.text_primary,
        edgecolors=color,
        linewidths=1.2,
        zorder=6,
    )

    ax.scatter(
        [
            columns[-1],
        ],
        [
            rows[-1],
        ],
        s=32,
        marker="*",
        color=THEME.winner,
        edgecolors=THEME.text_primary,
        linewidths=0.7,
        zorder=6,
    )


def _metric_text(
    evaluation_city: dict[str, object],
    method_id: str,
) -> str:
    methods = evaluation_city.get("methods")

    if not isinstance(
        methods,
        dict,
    ):
        raise TypeError("evaluation methods missing")

    method = methods.get(method_id)

    if not isinstance(
        method,
        dict,
    ):
        raise KeyError(f"evaluation method missing: {method_id}")

    travel_time = float(
        cast(
            float,
            method["travel_time"],
        )
    )

    risk = float(
        cast(
            float,
            method["true_cumulative_risk"],
        )
    )

    regret = float(
        cast(
            float,
            method["normalized_objective_regret"],
        )
    )

    return f"Time {travel_time:.1f}\nRisk {risk:.2f}\nRegret {regret:.3f}"


def render_opening_board(
    *,
    cities_payload: dict[str, object],
    routes_payload: dict[str, object],
    evaluation_payload: dict[str, object],
    output_path: Path,
) -> Path:
    """Render 3 cities x 3 methods opening board."""
    fig = _new_figure()

    fig.suptitle(
        "Who escapes best?",
        color=THEME.text_primary,
        fontsize=THEME.title_size,
        fontweight="bold",
        y=0.965,
    )

    fig.text(
        0.5,
        0.905,
        "Dijkstra vs ML vs Deep Learning",
        color=THEME.text_secondary,
        fontsize=THEME.subtitle_size,
        ha="center",
    )

    grid = fig.add_gridspec(
        3,
        3,
        left=0.06,
        right=0.96,
        bottom=0.08,
        top=0.88,
        wspace=0.08,
        hspace=0.10,
    )

    for row_index, city_id in enumerate(CITY_ORDER):
        city = _city_payload(
            cities_payload,
            city_id,
        )

        evaluation_city = _evaluation_city_payload(
            evaluation_payload,
            city_id,
        )

        winner = evaluation_city["winner_method"]

        for column_index, method_id in enumerate(METHOD_ORDER):
            ax = fig.add_subplot(
                grid[
                    row_index,
                    column_index,
                ]
            )

            _draw_city_base(
                ax,
                city,
            )

            route = _method_route(
                routes_payload,
                city_id,
                method_id,
            )

            _draw_route(
                ax,
                route,
                method_id,
            )

            label = METHOD_LABELS[method_id]

            if method_id == winner:
                label = f"{label}  ★"

            ax.set_title(
                label,
                color=(THEME.winner if method_id == winner else THEME.text_primary),
                fontsize=THEME.panel_title_size,
                fontweight="bold",
                pad=3,
            )

            ax.text(
                0.03,
                0.04,
                _metric_text(
                    evaluation_city,
                    method_id,
                ),
                transform=ax.transAxes,
                fontsize=THEME.metric_size,
                color=THEME.text_primary,
                va="bottom",
                ha="left",
                bbox={
                    "boxstyle": "round,pad=0.25",
                    "facecolor": THEME.background,
                    "edgecolor": THEME.panel_border,
                    "alpha": 0.82,
                },
                zorder=10,
            )

            if column_index == 0:
                ax.text(
                    -0.12,
                    0.5,
                    CITY_LABELS[city_id],
                    transform=ax.transAxes,
                    color=THEME.text_secondary,
                    fontsize=11,
                    fontweight="bold",
                    rotation=90,
                    va="center",
                    ha="center",
                )

    fig.text(
        0.5,
        0.025,
        (
            "Observed danger field • realized hidden-truth "
            "evaluation • oracle excluded from winner selection"
        ),
        color=THEME.text_muted,
        fontsize=THEME.footer_size,
        ha="center",
    )

    return _save_figure(
        fig,
        output_path,
    )


def render_city_frame(
    *,
    city_id: str,
    cities_payload: dict[str, object],
    routes_payload: dict[str, object],
    evaluation_payload: dict[str, object],
    output_path: Path,
) -> Path:
    """Render one city with three comparable method layers."""
    if city_id not in CITY_ORDER:
        raise KeyError(f"unknown showcase city: {city_id}")

    fig = _new_figure()

    evaluation_city = _evaluation_city_payload(
        evaluation_payload,
        city_id,
    )

    winner = cast(
        str,
        evaluation_city["winner_method"],
    )

    fig.suptitle(
        CITY_LABELS[city_id],
        color=THEME.text_primary,
        fontsize=THEME.title_size,
        fontweight="bold",
        y=0.955,
    )

    fig.text(
        0.5,
        0.915,
        ("Same destination. Same objective. Different risk estimate."),
        color=THEME.text_secondary,
        fontsize=THEME.subtitle_size,
        ha="center",
    )

    city = _city_payload(
        cities_payload,
        city_id,
    )

    grid = fig.add_gridspec(
        3,
        1,
        left=0.16,
        right=0.84,
        bottom=0.08,
        top=0.87,
        hspace=0.14,
    )

    for index, method_id in enumerate(METHOD_ORDER):
        ax = fig.add_subplot(
            grid[
                index,
                0,
            ]
        )

        _draw_city_base(
            ax,
            city,
        )

        route = _method_route(
            routes_payload,
            city_id,
            method_id,
        )

        _draw_route(
            ax,
            route,
            method_id,
        )

        label = METHOD_LABELS[method_id]

        if method_id == winner:
            label = f"{label} — CITY WINNER"

        ax.text(
            0.01,
            1.04,
            label,
            transform=ax.transAxes,
            color=(THEME.winner if method_id == winner else _route_color(method_id)),
            fontsize=11,
            fontweight="bold",
            ha="left",
            va="bottom",
        )

        ax.text(
            1.015,
            0.5,
            _metric_text(
                evaluation_city,
                method_id,
            ),
            transform=ax.transAxes,
            color=THEME.text_primary,
            fontsize=THEME.metric_size,
            ha="left",
            va="center",
            bbox={
                "boxstyle": "round,pad=0.35",
                "facecolor": THEME.panel_background,
                "edgecolor": _route_color(method_id),
            },
        )

    return _save_figure(
        fig,
        output_path,
    )


def render_final_summary(
    *,
    evaluation_payload: dict[str, object],
    output_path: Path,
) -> Path:
    """Render final cross-city winner summary."""
    fig = _new_figure()

    overall = evaluation_payload.get("overall")

    if not isinstance(
        overall,
        dict,
    ):
        raise TypeError("evaluation overall section missing")

    overall_winner = cast(
        str,
        overall["winner_method"],
    )

    fig.text(
        0.5,
        0.91,
        "Final Result",
        color=THEME.text_secondary,
        fontsize=THEME.subtitle_size,
        ha="center",
    )

    fig.text(
        0.5,
        0.835,
        (f"{METHOD_LABELS[overall_winner]} wins overall"),
        color=THEME.winner,
        fontsize=30,
        fontweight="bold",
        ha="center",
    )

    fig.text(
        0.5,
        0.785,
        ("Lowest mean normalized realized-objective regret across all three cities"),
        color=THEME.text_secondary,
        fontsize=11,
        ha="center",
    )

    raw_methods = overall.get("methods")

    if not isinstance(
        raw_methods,
        list,
    ):
        raise TypeError("overall.methods must be a list")

    method_rows = {
        cast(
            str,
            row["method_id"],
        ): cast(
            dict[str, object],
            row,
        )
        for row in raw_methods
        if isinstance(
            row,
            dict,
        )
    }

    left = 0.11
    width = 0.78
    top = 0.66
    row_height = 0.13

    headers = (
        "Method",
        "City wins",
        "Mean regret",
        "Mean risk",
        "Mean time",
    )

    header_x = (
        left,
        left + 0.30,
        left + 0.43,
        left + 0.58,
        left + 0.70,
    )

    for x, label in zip(
        header_x,
        headers,
        strict=True,
    ):
        fig.text(
            x,
            top,
            label,
            color=THEME.text_secondary,
            fontsize=10,
            fontweight="bold",
            ha="left",
        )

    for index, method_id in enumerate(METHOD_ORDER):
        row = method_rows[method_id]

        y = top - 0.075 - index * row_height

        is_winner = method_id == overall_winner

        fig.patches.append(
            matplotlib.patches.FancyBboxPatch(
                (
                    left - 0.02,
                    y - 0.04,
                ),
                width,
                0.085,
                boxstyle="round,pad=0.01",
                transform=fig.transFigure,
                facecolor=("#17352d" if is_winner else THEME.panel_background),
                edgecolor=(THEME.winner if is_winner else THEME.panel_border),
                linewidth=1.3,
            )
        )

        values = (
            METHOD_LABELS[method_id],
            str(row["city_wins"]),
            f"{float(cast(float, row['mean_normalized_objective_regret'])):.4f}",
            f"{float(cast(float, row['mean_true_cumulative_risk'])):.2f}",
            f"{float(cast(float, row['mean_travel_time'])):.1f}",
        )

        for x, value in zip(
            header_x,
            values,
            strict=True,
        ):
            fig.text(
                x,
                y,
                value,
                color=(THEME.winner if is_winner else THEME.text_primary),
                fontsize=10,
                fontweight=("bold" if is_winner else "normal"),
                ha="left",
                va="center",
            )

    city_y = 0.20

    fig.text(
        0.5,
        city_y + 0.08,
        "City winners",
        color=THEME.text_secondary,
        fontsize=11,
        fontweight="bold",
        ha="center",
    )

    raw_cities = evaluation_payload.get("cities")

    if not isinstance(
        raw_cities,
        list,
    ):
        raise TypeError("evaluation cities missing")

    by_city = {
        cast(
            str,
            city["city_id"],
        ): cast(
            dict[str, object],
            city,
        )
        for city in raw_cities
        if isinstance(
            city,
            dict,
        )
    }

    city_x = (
        0.22,
        0.50,
        0.78,
    )

    for x, city_id in zip(
        city_x,
        CITY_ORDER,
        strict=True,
    ):
        winner = cast(
            str,
            by_city[city_id]["winner_method"],
        )

        fig.text(
            x,
            city_y,
            CITY_LABELS[city_id],
            color=THEME.text_secondary,
            fontsize=10,
            ha="center",
        )

        fig.text(
            x,
            city_y - 0.045,
            METHOD_LABELS[winner],
            color=_route_color(winner),
            fontsize=11,
            fontweight="bold",
            ha="center",
        )

    fig.text(
        0.5,
        0.055,
        ("Oracle = hidden-truth-informed risk benchmark • not winner eligible"),
        color=THEME.text_muted,
        fontsize=THEME.footer_size,
        ha="center",
    )

    return _save_figure(
        fig,
        output_path,
    )


def add_method_legend(
    fig: Figure,
) -> None:
    """Add reusable method legend to a figure."""
    handles = [
        Patch(
            facecolor=_route_color(method_id),
            label=METHOD_LABELS[method_id],
        )
        for method_id in METHOD_ORDER
    ]

    fig.legend(
        handles=handles,
        loc="lower center",
        bbox_to_anchor=(
            0.5,
            0.015,
        ),
        ncol=3,
        frameon=False,
        labelcolor=THEME.text_secondary,
        fontsize=9,
    )


def validate_figure_geometry(
    figure: Figure,
) -> None:
    """Validate reusable figure geometry before export."""
    width, height = figure.get_size_inches()

    pixel_width = round(width * figure.dpi)

    pixel_height = round(height * figure.dpi)

    if pixel_width != CANVAS_SIZE or pixel_height != CANVAS_SIZE:
        raise ValueError(
            "visual frame must be exactly "
            f"{CANVAS_SIZE}x{CANVAS_SIZE}; "
            f"got {pixel_width}x{pixel_height}"
        )

    for ax in figure.axes:
        x0, y0, width, height = ax.get_position().bounds

        if (
            x0 < 0.0
            or y0 < 0.0
            or width <= 0.0
            or height <= 0.0
            or x0 + width > 1.0
            or y0 + height > 1.0
        ):
            raise ValueError("axis geometry extends outside canvas")


def validate_text_overlaps(
    figure: Figure,
) -> None:
    """Reject substantial overlaps among explicit figure-level text."""
    figure.canvas.draw()

    renderer = cast(
        _RendererCanvas,
        figure.canvas,
    ).get_renderer()

    texts = [
        text
        for text in figure.findobj(match=Text)
        if (text.get_visible() and text.get_text().strip() and text.axes is None)
    ]

    boxes = [
        (
            text,
            text.get_window_extent(renderer=renderer),
        )
        for text in texts
    ]

    for left_index, (
        left_text,
        left_box,
    ) in enumerate(boxes):
        for right_text, right_box in boxes[left_index + 1 :]:
            overlap_width = max(
                0.0,
                min(
                    left_box.x1,
                    right_box.x1,
                )
                - max(
                    left_box.x0,
                    right_box.x0,
                ),
            )

            overlap_height = max(
                0.0,
                min(
                    left_box.y1,
                    right_box.y1,
                )
                - max(
                    left_box.y0,
                    right_box.y0,
                ),
            )

            intersection = overlap_width * overlap_height

            if intersection <= 1.0:
                continue

            smaller = min(
                left_box.width * left_box.height,
                right_box.width * right_box.height,
            )

            if smaller > 0.0 and intersection / smaller > 0.20:
                raise ValueError(
                    "figure-level text overlap: "
                    f"{left_text.get_text()!r} vs "
                    f"{right_text.get_text()!r}"
                )


def render_preview_frames(
    *,
    data_directory: Path,
    output_directory: Path,
) -> PreviewArtifacts:
    """Render all Step 8 preview frames."""
    (
        cities_payload,
        _prediction_payload,
        routes_payload,
        evaluation_payload,
    ) = load_visual_payloads(data_directory)

    output_directory.mkdir(
        parents=True,
        exist_ok=True,
    )

    opening_path = output_directory / "opening_board.png"

    render_opening_board(
        cities_payload=cities_payload,
        routes_payload=routes_payload,
        evaluation_payload=evaluation_payload,
        output_path=opening_path,
    )

    city_paths = []

    for city_id in CITY_ORDER:
        city_path = output_directory / f"city_{city_id}.png"

        render_city_frame(
            city_id=city_id,
            cities_payload=cities_payload,
            routes_payload=routes_payload,
            evaluation_payload=evaluation_payload,
            output_path=city_path,
        )

        city_paths.append(city_path)

    final_path = output_directory / "final_summary.png"

    render_final_summary(
        evaluation_payload=evaluation_payload,
        output_path=final_path,
    )

    return PreviewArtifacts(
        opening_board=opening_path,
        city_frames=tuple(city_paths),
        final_summary=final_path,
    )


def _save_figure(
    figure: Figure,
    output_path: Path,
) -> Path:
    validate_figure_geometry(figure)

    validate_text_overlaps(figure)

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    figure.savefig(
        output_path,
        dpi=FIGURE_DPI,
        facecolor=THEME.background,
        bbox_inches=None,
        pad_inches=0.0,
    )

    plt.close(figure)

    return output_path
