"""Bayesian Dice Detective project package."""

from linkedin_visual_labs.projects.p01_bayesian_dice.config import (
    DEFAULT_CONFIG_PATH,
    DiceConfigurationError,
    load_dice_config,
)
from linkedin_visual_labs.projects.p01_bayesian_dice.models import (
    FACE_COUNT,
    PROBABILITY_SUM_TOLERANCE,
    BayesianModelDefinition,
    CalibrationDefinition,
    DecisionState,
    DecisionThresholds,
    DiceModelError,
    DiceProjectConfig,
    OutputContract,
    ProbabilityVector,
    ScenarioDefinition,
    VideoContract,
)
from linkedin_visual_labs.projects.p01_bayesian_dice.pipeline import (
    DicePipelineContext,
    build_pipeline_context,
)
from linkedin_visual_labs.projects.p01_bayesian_dice.simulation import (
    ROLL_HISTORY_COLUMNS,
    DiceSimulationError,
    RollRecord,
    SimulationResult,
    count_faces,
    cumulative_roll_records,
    generate_fair_rolls,
    generate_loaded_rolls,
    generate_rolls,
    simulate_scenario,
    simulation_required_fields,
    simulation_summary_line,
    summarize_simulation,
    validate_roll_count,
    validate_rolls,
    validate_simulation_payload,
    write_roll_history_csv,
    write_simulation_json,
)

__all__ = [
    "DEFAULT_CONFIG_PATH",
    "FACE_COUNT",
    "PROBABILITY_SUM_TOLERANCE",
    "ROLL_HISTORY_COLUMNS",
    "BayesianModelDefinition",
    "CalibrationDefinition",
    "DecisionState",
    "DecisionThresholds",
    "DiceConfigurationError",
    "DiceModelError",
    "DicePipelineContext",
    "DiceProjectConfig",
    "DiceSimulationError",
    "OutputContract",
    "ProbabilityVector",
    "RollRecord",
    "ScenarioDefinition",
    "SimulationResult",
    "VideoContract",
    "build_pipeline_context",
    "count_faces",
    "cumulative_roll_records",
    "generate_fair_rolls",
    "generate_loaded_rolls",
    "generate_rolls",
    "load_dice_config",
    "simulate_scenario",
    "simulation_required_fields",
    "simulation_summary_line",
    "summarize_simulation",
    "validate_roll_count",
    "validate_rolls",
    "validate_simulation_payload",
    "write_roll_history_csv",
    "write_simulation_json",
]
